import { config, fields, collection } from "@keystatic/core";

// 常用小說與設定集漢字拼音對照表，供自動 Slugify 使用
const PINYIN_MAP: Record<string, string> = {
  不: "bu",
  夜: "ye",
  侯: "hou",
  厲: "li",
  絕: "jue",
  鋒: "feng",
  司: "si",
  南: "nan",
  塵: "chen",
  燼: "jin",
  蠲: "juan",
  歲: "sui",
  戲: "xi",
  長: "chang",
  安: "an",
  摘: "zhai",
  雲: "yun",
  斬: "zhan",
  荒: "huang",
  飲: "yin",
  劫: "jie",
  晏: "yan",
  雪: "xue",
  楚: "chu",
  韶: "shao",
  華: "hua",
  樓: "lou",
  深: "shen",
  闕: "que",
  歧: "qi",
  歿: "mo",
  古: "gu",
  江: "jiang",
  無: "wu",
  岸: "an",
  澹: "dan",
  臺: "tai",
  翣: "sha",
  煙: "yan",
  蘿: "luo",
  白: "bai",
  檀: "tan",
  百: "bai",
  年: "nian",
  裁: "cai",
  罰: "fa",
  者: "zhe",
  研: "yan",
  辭: "ci",
  蒹: "jian",
  葭: "jia",
  蘇: "su",
  挽: "wan",
  風: "feng",
  陸: "lu",
  涯: "ya",
  雙: "shuang",
  魂: "hun",
  皇: "huang",
  帝: "di",
  九: "jiu",
  宮: "gong",
  格: "ge",
  乾: "qian",
  坤: "kun",
  秩: "zhi",
  序: "xu",
  矩: "ju",
  陣: "zhen",
  天: "tian",
  羃: "mi",
  遺: "yi",
  玉: "yu",
  六: "liu",
  器: "qi",
  本: "ben",
  源: "yuan",
  服: "fu",
  飾: "shi",
  性: "xing",
  表: "biao",
  象: "xiang",
  日: "ri",
  常: "chang",
  習: "xi",
  慣: "guan",
  瞳: "tong",
  孔: "kong",
  神: "shen",
  態: "tai",
  種: "zhong",
  族: "zu",
  血: "xue",
  統: "tong",
  膚: "fu",
  色: "se",
  外: "wai",
  貌: "mao",
  頭: "tou",
  髮: "fa",
  型: "xing",
  特: "te",
  殊: "shu",
  能: "neng",
  力: "li",
  全: "quan",
  維: "wei",
  徵: "zheng",
  美: "mei",
  學: "xue",
  總: "zong",
  綱: "gang",
  舊: "jiu",
  世: "shi",
  中: "zhong",
  陰: "yin",
  界: "jie",
  角: "jiao",
  設: "she",
  草: "cao",
  案: "an",
  擴: "kuo",
  充: "chong",
  組: "zu",
  織: "zhi",
  正: "zheng",
  派: "pai",
  提: "ti",
  浮: "fu",
  生: "sheng",
  極: "ji",
  樂: "le",
  坊: "fang",
  定: "ding",
  碑: "bei",
  內: "nei",
  部: "bu",
  構: "gou",
  造: "zao",
  級: "ji",
  勢: "shi",
  質: "zhi",
  詞: "ci",
  條: "tiao",
  庫: "ku",
  觀: "guan",
  星: "xing",
  閣: "ge",
};

function pinyinSlugify(text: string): string {
  if (!text) return "";
  const hasChinese = /[\u4e00-\u9fa5]/.test(text);
  if (!hasChinese) {
    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "");
  }
  const chars = Array.from(text);
  const result = chars
    .map((char) => {
      if (/[a-zA-Z0-9]/.test(char)) return char.toLowerCase();
      if (PINYIN_MAP[char]) return PINYIN_MAP[char];
      return "";
    })
    .filter(Boolean)
    .join("-");
  return result.replace(/-+/g, "-").replace(/(^-|-$)/g, "");
}

export default config({
  storage: import.meta.env.DEV
    ? { kind: "local" as const }
    : { kind: "cloud" as const },
  cloud: { project: "meng10730/meng10730-github-io" },
  collections: {
    blog: collection({
      label: "部落格文章",
      slugField: "title",
      path: "src/content/blog/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "標題" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({ label: "簡介", multiline: true }),
        pubDate: fields.date({ label: "發布日期" }),
        tags: fields.array(fields.text({ label: "標籤" }), {
          label: "標籤",
          itemLabel: (props) => props.value,
        }),
        content: fields.mdx({ label: "內文", extension: "md" }),
      },
    }),
    works: collection({
      label: "作品集專案",
      slugField: "title",
      path: "src/content/works/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "專案名稱" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({ label: "一句話描述" }),
        category: fields.select({
          label: "分類",
          options: [
            { label: "Web", value: "web" },
            { label: "Game", value: "game" },
            { label: "Other", value: "other" },
          ],
          defaultValue: "web",
        }),
        techs: fields.array(fields.text({ label: "使用技術標籤" }), {
          label: "技術標籤",
          itemLabel: (props) => props.value,
        }),
        status: fields.select({
          label: "狀態",
          options: [
            { label: "已完成 (completed)", value: "completed" },
            { label: "進行中 (ongoing)", value: "ongoing" },
            { label: "已封存 (archived)", value: "archived" },
          ],
          defaultValue: "completed",
        }),
        github: fields.url({ label: "GitHub 連結 (選填)" }),
        demo: fields.url({ label: "Live Demo 連結 (選填)" }),
        pubDate: fields.date({ label: "完成或發布日期" }),
        content: fields.mdx({ label: "專案詳細介紹 (內文)", extension: "md" }),
      },
    }),
    novels: collection({
      label: "小說連載 (山莊)",
      slugField: "title",
      path: "src/content/novels/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "小說標題" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({ label: "簡介", multiline: true }),
        genre: fields.array(fields.text({ label: "類型標籤 (武俠、仙俠…)" }), {
          label: "類型",
          itemLabel: (props) => props.value,
        }),
        status: fields.select({
          label: "連載狀態",
          options: [
            { label: "連載中 (ongoing)", value: "ongoing" },
            { label: "已完結 (completed)", value: "completed" },
            { label: "停更 (hiatus)", value: "hiatus" },
          ],
          defaultValue: "ongoing",
        }),
        pubDate: fields.date({ label: "開始連載日期" }),
        cover: fields.image({
          label: "封面圖",
          directory: "public/images/novels",
          publicPath: "/images/novels",
        }),
        content: fields.mdx({ label: "內文 / 大綱", extension: "md" }),
      },
    }),
    characters: collection({
      label: "人物設定 (山莊)",
      slugField: "name",
      path: "src/content/characters/*",
      format: { contentField: "content" },
      schema: {
        name: fields.slug({
          name: { label: "人物名稱" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({
          label: "人物簡介 (用於前台懸浮氣泡，選填)",
          multiline: true,
        }),
        alias: fields.array(fields.text({ label: "別名 / 江湖稱號" }), {
          label: "別名",
          itemLabel: (props) => props.value,
        }),
        affiliation: fields.text({ label: "所屬門派或陣營" }),
        novel: fields.text({ label: "所屬小說名稱" }),
        tags: fields.array(fields.text({ label: "標籤 (主角、反派…)" }), {
          label: "標籤",
          itemLabel: (props) => props.value,
        }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細人物傳記 / 設定", extension: "md" }),
      },
    }),
    worldview: collection({
      label: "世界觀設定 (山莊)",
      slugField: "title",
      path: "src/content/worldview/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "設定標題" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({
          label: "設定簡介 (用於前台懸浮氣泡，選填)",
          multiline: true,
        }),
        category: fields.text({ label: "分類 (例：機制、地理、神明體系)" }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細設定內文", extension: "md" }),
      },
    }),
    factions: collection({
      label: "勢力組織 (山莊)",
      slugField: "title",
      path: "src/content/factions/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "勢力名稱" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        description: fields.text({
          label: "勢力簡介 (用於前台懸浮氣泡，選填)",
          multiline: true,
        }),
        category: fields.text({ label: "分類 (例：正派、地下、世俗、中立)" }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細勢力內文", extension: "md" }),
      },
    }),
    guoxue: collection({
      label: "國學筆記 (山莊)",
      slugField: "title",
      path: "src/content/guoxue/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "筆記標題" },
          slug: {
            label: "網址別名 (Slug)",
            description: "此欄位若留空，純中文標題會自動轉為拼音",
            slugify: pinyinSlugify,
          },
        }),
        source: fields.text({ label: "出處 (論語、道德經…)" }),
        category: fields.select({
          label: "分類",
          options: [
            { label: "儒家 (confucianism)", value: "confucianism" },
            { label: "道家 (taoism)", value: "taoism" },
            { label: "佛家 (buddhism)", value: "buddhism" },
            { label: "史學 (history)", value: "history" },
            { label: "詩詞 (poetry)", value: "poetry" },
            { label: "其他 (other)", value: "other" },
          ],
          defaultValue: "other",
        }),
        tags: fields.array(fields.text({ label: "標籤" }), {
          label: "標籤",
          itemLabel: (props) => props.value,
        }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "筆記內文", extension: "md" }),
      },
    }),
    items: collection({
      label: "法寶神兵 (山莊)",
      slugField: "title",
      path: "src/content/items/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "法寶名稱" },
          slug: { label: "網址別名 (Slug)", slugify: pinyinSlugify },
        }),
        description: fields.text({ label: "簡介", multiline: true }),
        novel: fields.text({ label: "所屬作品 (預設: 長生劫)" }),
        rank: fields.text({ label: "品階 (如: 地級、先天靈寶)" }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細設定內文", extension: "md" }),
      },
    }),
    techniques: collection({
      label: "功法秘笈 (山莊)",
      slugField: "title",
      path: "src/content/techniques/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "功法名稱" },
          slug: { label: "網址別名 (Slug)", slugify: pinyinSlugify },
        }),
        description: fields.text({ label: "簡介", multiline: true }),
        novel: fields.text({ label: "所屬作品 (預設: 長生劫)" }),
        type: fields.text({ label: "功法類型 (如: 心法、劍訣)" }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細設定內文", extension: "md" }),
      },
    }),
    bestiary: collection({
      label: "靈獸妖魔 (山莊)",
      slugField: "title",
      path: "src/content/bestiary/*",
      format: { contentField: "content" },
      schema: {
        title: fields.slug({
          name: { label: "名稱" },
          slug: { label: "網址別名 (Slug)", slugify: pinyinSlugify },
        }),
        description: fields.text({ label: "簡介", multiline: true }),
        novel: fields.text({ label: "所屬作品 (預設: 長生劫)" }),
        pubDate: fields.date({ label: "建立日期" }),
        content: fields.mdx({ label: "詳細設定內文", extension: "md" }),
      },
    }),
    // [ADD_NEW_COLLECTION_KEYSTATIC_HERE]
  },
});
